### ISSUE TITLE
Task - 1 Creare la struttura per le abitudini ricorrenti

### ISSUE THREAD

**Issue by NasoAQ** [tomorrowdevs-projects/tech-jobs-fair-roma-2024-team4#10]
### Obiettivo:
Creare la struttura per gestire le abitudini ricorrenti nel database Firestore. Ogni abitudine deve poter avere una frequenza variabile: giornaliera, settimanale, mensile, o in giorni specifici.

### Task:
1. Definire il modello dati per le abitudini in Firestore.
2. Implementare la logica per memorizzare la frequenza ricorrente (giornaliera, settimanale, mensile).
3. Supportare la selezione di giorni specifici della settimana o del mese.

### Milestone:
Inserimento di abitudini ricorrenti

**Comment by TommasoScalici** [comment]
1. Fatto
2. Fatto
3. Per semplicità (e mancanza di tempo) la selezione della frequenza viene fatto con input numerico che stabilisce ogni quanti giorni/settimane/mesi l'evento deve ripetersi, non c'è un selettore dei giorni specifici della settimana (tipo "ogni martedì", "ogni giovedì" ecc.)
