### ISSUE TITLE
Task - 3 Logica per il completamento delle abitudini

### ISSUE THREAD

**Issue by NasoAQ** [tomorrowdevs-projects/tech-jobs-fair-roma-2024-team4#12]
### Obiettivo:
Implementare la logica che permette di tracciare il completamento delle abitudini ricorrenti. L'abitudine deve poter essere segnata come completata e il sistema deve gestire la ricorrenza in base alla frequenza scelta.

### Task:
1. Implementare la logica nel backend per tracciare il completamento dell'abitudine.
2. Gestire l'aggiornamento automatico della prossima occorrenza dell'abitudine ricorrente.
3. Salvare lo stato di completamento in Firestore.

### Milestone:
Inserimento di abitudini ricorrenti

**Comment by francescosave** [comment]
1. Implementare la logica nel backend per tracciare il completamento dell'abitudine.

In riferimento a questa logica bisogna distinguere tra Ricorrenza/Frequenza.
Partiamo dalle tre basilari giornaliera settimanale e mensile.

Io separerei la logica tra giornaliera e non giornaliera.
Nella giornaliera viene semplice perchè l'habit avviene una volta nei giorni (inseriti nell'array) tra l'intervallo delle due date.

Nel caso di settimanale e mensile 
L'habit avviene una volta nelle settimane (calcolate e inserito il giorno in base alla data inizio) tra l'intervallo delle due date.
Esempio.
habit settimanale tra il lunedi 23 settmbre 24 e domenica 6 ottobre

Calcolo son due settimane 
23/9/24 - 29/9/24
30/9/24 - 06/10/24
Prende il primo giorno e notifica 23 e *30 (23+7*1) .

L'habit viene tracciata com non completata solo all'ultimo giorno (dopo la notifica).
Esempio solo il 30 dopo la notifica

**Comment by francescosave** [comment]
Tecnicamente tracciare e aggiornare l'habit come completata è legato alle notifiche,non so se cosi viene semplice.
Per semplificare in base alla logica tracciare completato solo l'intero habit piuttosto che le singole date.
