### ISSUE TITLE
Task - Griglia Allday/Orario

### ISSUE THREAD

**Issue by abuonom** [tomorrowdevs-projects/tech-jobs-fair-roma-2024-team4#18]
Suddividere la griglia in più sezioni per ottenere task "All Day" e task "Orario" in due gruppi diversi

**Comment by TommasoScalici** [comment]
Fatto, la suddivisione alla fine è stata fatta in 4 griglie

1) Task "all day"
2) Task nella fascia oraria "mattina"
3) Task nella fascia oraria "pomeriggio"
4) Task nella fascia oraria "sera"
